import fs from "fs"
const file = fs.readFileSync("inputs/day-7.txt").toString()
const example = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
`

let counter = 0
const map = file.split("\n").map(e => e.split(""))
const beams = [[0, map[0]?.findIndex(e => e === 'S')]]
const visited = new Set()
while (beams.length > 0) {
  const beam = beams.shift()! as [number, number]
  if (visited.has(JSON.stringify(beam))) {
    continue
  }
  visited.add(JSON.stringify(beam))
  if (map[beam[0] + 1]?.[beam[1]] === '.') {
    beams.push([beam[0] + 1, beam[1]])
  } else if (map[beam[0] + 1]?.[beam[1]] === '^') {
    counter++
    beams.push([beam[0] + 1, beam[1] - 1])
    beams.push([beam[0] + 1, beam[1] + 1])
  }
}


console.log(counter)